id: IF44DF4F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:37:29+00:00'
last_modified: '2022-06-09T06:16:49.054024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137843
  title: བོད་རྒྱ་སྐར་རྩིས་རིག་པའི་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    731B:
      image_group_id: I2PD19674
      title: Volume 1 of bod rgya skar rtsis rig pa'i tshig mdzod/
      total_pages: 256
      order: 1
      base_file: 731B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
