id: P007128
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137843
  title: བོད་རྒྱ་སྐར་རྩིས་རིག་པའི་ཚིག་མཛོད།
  author: ''
  volumes:
    98e79a3d1cc1404188e4258a926f7b7b:
      image_group_id: I2PD19674
      title: ''
      volume_number: 1
      total_pages: 256
ebook_metadata:
  title: བོད་རྒྱ་སྐར་རྩིས་རིག་པའི་ཚིག་མཛོད།
  author: ''
  sku: P007128
  cover: cover.jpg
  layers:
  - pagination
