id: P007128
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:43:31.505533
source_metadata:
  id: bdr:W1PD137843
  title: བོད་རྒྱ་སྐར་རྩིས་རིག་པའི་ཚིག་མཛོད།
  author: ''
  volumes:
    ef5b5756043a4d9097d253c9f378ff94:
      image_group_id: I2PD19674
      title: Volume 1 of bod rgya skar rtsis rig pa'i tshig mdzod/
      volume_number: 1
      total_pages: 256
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
